### ISSUE TITLE
Doubt about logout

### ISSUE THREAD

**Issue by aldemirfilho** [edwin/spring-3-keycloak#1]
Hello, first of all, thank you very much for your material, it was the only one that helped me with exactly what I wanted!

I would like to know how to log out after being authenticated. What would my URL be like that, when accessed, would cause the logout to be performed? I would like to know how to create a button in the application, which when clicked automatically disconnects you.

If possible, I would also like to know if it is possible to collect basic data, such as the name, for example, of the user who has just authenticated, to be able to display it in the application.

Thank you very much!

Att,
Aldemir Melo

**Comment by edwin** [comment]
Hi @aldemirfilho 
you can see how Keycloak handle logouts on my other article,
```
https://developers.redhat.com/articles/2022/12/07/how-implement-single-sign-out-keycloak-spring-boot
```

thank you.

**Comment by edwin** [comment]
>If possible, I would also like to know if it is possible to collect basic data, such as the name, for example, of the user who has just authenticated, to be able to display it in the application.

yes, you can do that like this
https://github.com/edwin/spring-3-keycloak/blob/master/src/main/java/com/edw/controller/IndexController.java#L26

**Comment by aldemirfilho** [comment]
Thank you very much for the material, I will study them!
